name: SSH Smoke
on: workflow_dispatch

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Try manual SSH
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          KEY:  ${{ secrets.VPS_SSH_KEY }}
          PORT: ${{ secrets.VPS_PORT || '22' }}
        run: |
          set -euxo pipefail
          echo "$KEY" > key.pem
          chmod 600 key.pem
          ssh-keygen -yf key.pem > pub.tmp
          ssh-keygen -lf pub.tmp || true
          ssh -vvv -o StrictHostKeyChecking=no -i key.pem -p "$PORT" "$USER@$HOST" 'echo OK_FROM_SERVER'
